INSERT INTO role (name) VALUES ('ADMINISTRADOR');
INSERT INTO role (name) VALUES ('AUTONOMO');
INSERT INTO role (name) VALUES ('CONTRATADO');
INSERT INTO role (name) VALUES ('GESTOR');
INSERT INTO role (name) VALUES ('SUPERADMIN');